/// Flutter icons PlayifyIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlayifyIcon
///      fonts:
///       - asset: fonts/PlayifyIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PlayifyIcon {
  PlayifyIcon._();

  static const _kFontFam = 'PlayifyIcon';
  static const _kFontPkg = null;

  static const IconData album = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData artist = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData song = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
